nombre=input("ingrese su nombre:")
print("hola",nombre,"mucho gusto")
nombre1=input("ingrese su nombre:")
edad=int(input("ingrese su edad"))
print("hola",nombre1,"que bueno que tengas",edad,"años")
ciudad=input("ingrese su ciudad")
print("hola yo tambien soy de ahi",ciudad)
num1=int(input("ingrese un numero"))
num2=int(input("ingrese el segundo numero"))
exponente1=int(input("ingrese el primer exponente "))
exponente2=int(input("ingrese el segundo exponente "))
resultado=num1*exponente1,num2 ** exponente2
print("la potenciacion de los numeros es:",resultado)
z=int(input("ingrese el numero deseado"))
a=int(input("ingrese el numero deseado"))
print("la multiplicacion de los numeros es:",z*a)
print("la division de los numeros es:",z//a)